# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bf9df261bba9e88640a57c526ed9565ab36c176339870889a7a568ca9d2195ef790e545308674dce75faf9cf6e00b0169a9fd1bad0e18a4af0554a76b6ed471

test:
  secret_key_base: 3926d81949289f13d4e7440c766c81395c9ba22a2e3f57a95283e15de15ae387f14eb0481ca1082922dc9e7236041866345a2510862947a8e09ee8c949df3362

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
